version: '3'

services:
  exercism:
    build: .
    image: brainpower/rust-exercism-cubicle
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - "8443:8443"
    volumes:
      - ".:/repo/"
      - "$SSH_AUTH_SOCK:/ssh-agent"
    environment:
      SSH_AUTH_SOCK: "/ssh-agent"
    working_dir: "/repo"
    entrypoint: ["code-server", "--allow-http", "--no-auth"]
