version: '3'

services:
  exercism:
    build: .
    image: brainpower/rust-exercism-cubicle
    ports:
      - '8443:8443'
    volumes:
      - ".:/root/project/"
    environment:
      - CARGO_TARGET_DIR=/home/rust/target
    command: /usr/bin/code-server --production --allow-http --no-auth /root/project
