version: 2
jobs:
  build:
    docker:
      - image: brainpower/rust-exercism-cubicle
    environment:
      CARGO_TARGET_DIR: /home/rust/target
    working_directory: /home/rust/repo
    steps:
      - checkout:
          path: /home/rust/repo
      - run:
          name: Test
          command: cargo test